import {
  Award,
  BadgeCheck,
  BatteryCharging,
  Bike,
  CalendarCheck,
  Check,
  CheckCheck,
  CircleCheck,
  Clock,
  CreditCard,
  Crown,
  Droplet,
  Feather,
  Flame,
  Gem,
  Gift,
  Handshake,
  Heart,
  HeartHandshake,
  Leaf,
  Lock,
  Medal,
  MessageCircleHeart,
  Package,
  PiggyBank,
  Plane,
  RefreshCcw,
  Ribbon,
  Rocket,
  ShieldCheck,
  Sparkle,
  Sparkles,
  Star,
  Sun,
  ThumbsUp,
  Timer,
  Truck,
  Undo2,
  Users,
  Wallet,
  Waves,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Curated professional icon set exposed in the theme editor */
export const themeIcons: Record<string, LucideIcon> = {
  check: Check,
  checkCheck: CheckCheck,
  circleCheck: CircleCheck,
  badgeCheck: BadgeCheck,
  shield: ShieldCheck,
  lock: Lock,
  truck: Truck,
  plane: Plane,
  package: Package,
  bike: Bike,
  undo: Undo2,
  refresh: RefreshCcw,
  wallet: Wallet,
  card: CreditCard,
  piggy: PiggyBank,
  gift: Gift,
  heart: Heart,
  heartHands: HeartHandshake,
  reviewHeart: MessageCircleHeart,
  handshake: Handshake,
  star: Star,
  sparkles: Sparkles,
  sparkle: Sparkle,
  crown: Crown,
  gem: Gem,
  medal: Medal,
  award: Award,
  ribbon: Ribbon,
  thumbsUp: ThumbsUp,
  users: Users,
  clock: Clock,
  timer: Timer,
  calendar: CalendarCheck,
  zap: Zap,
  battery: BatteryCharging,
  rocket: Rocket,
  flame: Flame,
  droplet: Droplet,
  waves: Waves,
  leaf: Leaf,
  feather: Feather,
  sun: Sun,
};

export const iconNames = Object.keys(themeIcons);

export const iconLabels: Record<string, string> = {
  check: "Coche",
  checkCheck: "Double coche",
  circleCheck: "Coche cerclée",
  badgeCheck: "Badge vérifié",
  shield: "Bouclier",
  lock: "Cadenas",
  truck: "Camion",
  plane: "Avion",
  package: "Colis",
  bike: "Vélo",
  undo: "Retour",
  refresh: "Échange",
  wallet: "Portefeuille",
  card: "Carte bancaire",
  piggy: "Économies",
  gift: "Cadeau",
  heart: "Cœur",
  heartHands: "Cœur mains",
  reviewHeart: "Avis",
  handshake: "Confiance",
  star: "Étoile",
  sparkles: "Étincelles",
  sparkle: "Étincelle",
  crown: "Couronne",
  gem: "Gemme",
  medal: "Médaille",
  award: "Récompense",
  ribbon: "Ruban",
  thumbsUp: "Pouce levé",
  users: "Clientes",
  clock: "Horloge",
  timer: "Chrono",
  calendar: "Calendrier",
  zap: "Éclair",
  battery: "Recharge",
  rocket: "Fusée",
  flame: "Flamme",
  droplet: "Goutte",
  waves: "Vagues",
  leaf: "Feuille",
  feather: "Plume",
  sun: "Soleil",
};

export const getIcon = (name: string, fallback: LucideIcon = Check): LucideIcon =>
  themeIcons[name] ?? fallback;

export function ThemeIcon({
  name,
  size = 16,
  className,
  color,
  fallback,
}: {
  name: string;
  size?: number;
  className?: string;
  color?: string;
  fallback?: LucideIcon;
}) {
  const Icon = getIcon(name, fallback ?? Check);
  return <Icon size={size} className={className} {...(color ? { color } : {})} />;
}
