import {
  AlignLeft,
  BadgeCheck,
  Contact,
  Copyright,
  Gauge,
  GitCompareArrows,
  HelpCircle,
  Images,
  LayoutTemplate,
  Megaphone,
  MessageSquareQuote,
  MousePointerClick,
  Navigation,
  Newspaper,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  Waves,
  Minus,
  type LucideIcon,
} from "lucide-react";
import type { ComponentType } from "react";
import type { Field, SectionType, Settings } from "./types";
import {
  AnnouncementSection,
  BeforeAfterSection,
  BenefitsSection,
  ComparisonSection,
  ContactSection,
  CtaSection,
  DividerSection,
  WavesSection,
  FaqSection,
  FooterSection,
  GuaranteeSection,
  HeaderSection,
  HeroSection,
  HomeHeroSection,
  HowToSection,
  MarqueeSection,
  PressSection,
  ReviewsSection,
  SocialSection,
  StatsSection,
  UspSection,
  type SectionProps,
} from "@/components/theme/sections";

export type SectionDefinition = {
  type: SectionType;
  label: string;
  icon: LucideIcon;
  /** Sections that should stay unique in the page (header, footer...) */
  unique?: boolean;
  /** Sections that live in the shared chrome instead of a page */
  chrome?: boolean;
  component: ComponentType<SectionProps>;
  schema: Field[];
  defaults: Settings;
};

const textList = (key: string, label: string, withIcon = false): Field => ({
  key,
  label,
  type: "list",
  itemFields: withIcon
    ? [
        { key: "text", label: "Texte", type: "text" },
        { key: "icon", label: "Icône", type: "icon" },
      ]
    : [{ key: "text", label: "Texte", type: "text" }],
  itemLabelKey: "text",
});

const linkList = (key: string, label: string): Field => ({
  key,
  label,
  type: "list",
  itemFields: [
    { key: "label", label: "Libellé", type: "text" },
    { key: "path", label: "Lien (ex : /produit)", type: "text" },
  ],
  itemLabelKey: "label",
});

/** Powerful Trustpilot / social-proof controls, reusable by any section */
const trustFields: Field[] = [
  { key: "showTrust", label: "Afficher la preuve sociale", type: "switch", group: "Trustpilot" },
  { key: "trustShowStars", label: "Afficher les étoiles", type: "switch", group: "Trustpilot" },
  {
    key: "trustStars",
    label: "Étoiles pleines",
    type: "range",
    min: 0,
    max: 5,
    unit: "★",
    group: "Trustpilot",
  },
  { key: "trustStarColor", label: "Couleur des étoiles", type: "color", group: "Trustpilot" },
  { key: "trustStarEmpty", label: "Couleur étoiles vides", type: "color", group: "Trustpilot" },
  { key: "trustRating", label: "Note (ex : 4,8/5)", type: "text", group: "Trustpilot" },
  {
    key: "trustShowLogo",
    label: "Afficher le logo Trustpilot",
    type: "switch",
    group: "Trustpilot",
  },
  { key: "trustLogoText", label: "Nom de la plateforme", type: "text", group: "Trustpilot" },
  { key: "trustBadge", label: "Texte du badge (nombre d'avis)", type: "text", group: "Trustpilot" },
];

const trustDefaults: Settings = {
  showTrust: true,
  trustShowStars: true,
  trustStars: 5,
  trustStarColor: "#00b67a",
  trustStarEmpty: "#e6e6e6",
  trustRating: "4,8/5",
  trustShowLogo: false,
  trustLogoText: "Avis clients",
  trustBadge: "Clients satisfaits",
};

export const sectionDefinitions: Record<SectionType, SectionDefinition> = {
  announcement: {
    type: "announcement",
    label: "Barre d'annonce",
    icon: Megaphone,
    unique: true,
    chrome: true,
    component: AnnouncementSection,
    schema: [
      textList("items", "Messages défilants"),
      {
        key: "autoScroll",
        label: "Défilement automatique",
        type: "switch",
        group: "Défilement",
      },
      {
        key: "speed",
        label: "Durée d'un cycle",
        type: "range",
        min: 5,
        max: 90,
        step: 1,
        unit: "s",
        group: "Défilement",
      },
      {
        key: "direction",
        label: "Sens du défilement",
        type: "select",
        options: [
          { value: "left", label: "Vers la gauche" },
          { value: "right", label: "Vers la droite" },
        ],
        group: "Défilement",
      },
      {
        key: "pauseOnHover",
        label: "Mettre en pause au survol",
        type: "switch",
        group: "Défilement",
      },
      {
        key: "gap",
        label: "Espace entre les messages",
        type: "range",
        min: 8,
        max: 96,
        step: 2,
        unit: "px",
        group: "Défilement",
      },
    ],
    defaults: {
      items: [
        { text: "Livraison rapide {{country}}" },
        { text: "Paiement à la livraison disponible" },
        { text: "Service client sur WhatsApp" },
      ],
      autoScroll: true,
      speed: 28,
      direction: "left",
      pauseOnHover: true,
      gap: 32,
    },
  },

  header: {
    type: "header",
    label: "En-tête",
    icon: Navigation,
    unique: true,
    chrome: true,
    component: HeaderSection,
    schema: [
      { key: "brand", label: "Nom de la marque", type: "text" },
      linkList("links", "Liens de navigation"),
      { key: "showCta", label: "Afficher le bouton", type: "switch" },
      { key: "ctaLabel", label: "Texte du bouton", type: "text" },
      { key: "ctaPath", label: "Lien du bouton", type: "text" },
      { key: "showCart", label: "Afficher le panier", type: "switch" },
    ],
    defaults: {
      brand: "{{store}}",
      showCta: true,
      ctaLabel: "Commander",
      ctaPath: "/produit",
      showCart: true,
      links: [
        { label: "Accueil", path: "/" },
        { label: "Nos produits", path: "/produit" },
        { label: "Contact", path: "/contact" },
      ],
    },
  },
  homeHero: {
    type: "homeHero",
    label: "Hero accueil",
    icon: LayoutTemplate,
    component: HomeHeroSection,
    schema: [
      { key: "eyebrow", label: "Sur-titre", type: "text" },
      { key: "title", label: "Titre", type: "text" },
      { key: "titleAccent", label: "Titre (partie colorée)", type: "text" },
      { key: "subtitle", label: "Sous-titre", type: "textarea" },
      textList("bullets", "Points forts", true),
      { key: "ctaLabel", label: "Bouton", type: "text" },
      { key: "ctaPath", label: "Lien du bouton", type: "text" },
      { key: "note", label: "Note sous le bouton", type: "text" },
      { key: "image", label: "Image", type: "image" },
      { key: "floatLabel", label: "Badge flottant — titre", type: "text" },
      { key: "floatText", label: "Badge flottant — texte", type: "text" },
      ...trustFields,
    ],
    defaults: {
      ...trustDefaults,
      eyebrow: "Bienvenue chez {{store}}",
      title: "Vos produits préférés,",
      titleAccent: "livrés chez vous",
      subtitle: "{{description}}",
      bullets: [
        { text: "Produits sélectionnés avec soin" },
        { text: "Paiement à la livraison ou Mobile Money" },
        { text: "Livraison rapide et suivie" },
      ],
      ctaLabel: "Découvrir la boutique",
      ctaPath: "/produit",
      note: "Commande simple · Paiement sécurisé",
      image: "",
      floatLabel: "Clients satisfaits",
      floatText: "Service client réactif",
    },
  },
  hero: {
    type: "hero",
    label: "Hero produit (offre)",
    icon: Sparkles,
    component: HeroSection,
    schema: [
      { key: "title", label: "Titre", type: "text" },
      { key: "subtitle", label: "Sous-titre", type: "textarea" },
      { key: "price", label: "Prix", type: "text" },
      { key: "compareAt", label: "Prix barré", type: "text" },
      { key: "saveLabel", label: "Badge d'économie", type: "text" },
      { key: "ctaLabel", label: "Bouton", type: "text" },
      { key: "ctaNote", label: "Note sous le bouton", type: "text" },
      { key: "showBadge", label: "Afficher le badge promo", type: "switch" },
      { key: "badge", label: "Texte du badge", type: "text" },
      textList("bullets", "Réassurances", true),
      { key: "showGift", label: "Afficher le cadeau offert", type: "switch", group: "Cadeau" },
      { key: "giftTitle", label: "Titre du cadeau", type: "text", group: "Cadeau" },
      { key: "giftText", label: "Texte du cadeau", type: "textarea", group: "Cadeau" },
      { key: "giftImage", label: "Image du cadeau", type: "image", group: "Cadeau" },
      { key: "showTiers", label: "Afficher les packs", type: "switch", group: "Packs" },
      {
        key: "tiers",
        label: "Offres (packs)",
        type: "list",
        group: "Packs",
        itemFields: [
          { key: "label", label: "Libellé", type: "text" },
          { key: "price", label: "Prix", type: "text" },
          { key: "compareAt", label: "Prix barré", type: "text" },
          { key: "saveLabel", label: "Badge économie", type: "text" },
          { key: "tag", label: "Étiquette (ex : le plus choisi)", type: "text" },
          { key: "image", label: "Image", type: "image" },
        ],
        itemLabelKey: "label",
      },
      {
        key: "images",
        label: "Galerie",
        type: "list",
        itemFields: [{ key: "url", label: "Image", type: "image" }],
        itemLabelKey: "url",
      },
      {
        key: "showPayments",
        label: "Afficher les logos de paiement",
        type: "switch",
        group: "Paiement",
      },
      {
        key: "payments",
        label:
          "Moyens de paiement (Visa, Mastercard, Amex, Apple Pay, G Pay, Shop, Discover, PayPal, Klarna)",
        type: "list",
        group: "Paiement",
        itemFields: [{ key: "label", label: "Marque", type: "text" }],
        itemLabelKey: "label",
      },
      {
        key: "showGuarantee",
        label: "Afficher garantie & paiements",
        type: "switch",
        group: "Garantie & paiements",
      },
      {
        key: "guaranteeTitle",
        label: "Titre de la garantie",
        type: "text",
        group: "Garantie & paiements",
      },
      {
        key: "guaranteeText",
        label: "Texte de la garantie",
        type: "textarea",
        group: "Garantie & paiements",
      },
      {
        key: "guaranteeIcon",
        label: "Icône de la garantie",
        type: "icon",
        group: "Garantie & paiements",
      },
      {
        key: "guaranteeIconColor",
        label: "Couleur des icônes",
        type: "color",
        group: "Garantie & paiements",
      },
      {
        key: "guaranteeIconBg",
        label: "Fond de l'icône",
        type: "color",
        group: "Garantie & paiements",
      },
      { key: "guaranteeBg", label: "Fond du bloc", type: "color", group: "Garantie & paiements" },
      {
        key: "guaranteeBorderColor",
        label: "Couleur de la bordure",
        type: "color",
        group: "Garantie & paiements",
      },
      {
        key: "guaranteePayments",
        label: "Logos de paiement",
        type: "list",
        group: "Garantie & paiements",
        itemFields: [{ key: "label", label: "Marque", type: "text" }],
        itemLabelKey: "label",
      },
      {
        key: "guaranteeItems",
        label: "Réassurances",
        type: "list",
        group: "Garantie & paiements",
        itemFields: [
          { key: "label", label: "Libellé", type: "text" },
          { key: "icon", label: "Icône", type: "icon" },
        ],
        itemLabelKey: "label",
      },
      { key: "showFaq", label: "Afficher la mini-FAQ", type: "switch", group: "Mini-FAQ" },
      { key: "faqTitle", label: "Titre de la mini-FAQ", type: "text", group: "Mini-FAQ" },
      {
        key: "faqItems",
        label: "Questions",
        type: "list",
        group: "Mini-FAQ",
        itemFields: [
          { key: "question", label: "Question", type: "text" },
          { key: "answer", label: "Réponse", type: "textarea" },
        ],
        itemLabelKey: "question",
      },
      ...trustFields,
    ],
    defaults: {
      ...trustDefaults,
      title: "{{product}}",
      subtitle: "{{productDescription}}",
      price: "{{price}}",
      compareAt: "",
      saveLabel: "",
      ctaLabel: "Ajouter au panier",
      ctaNote: "Paiement sécurisé · Livraison rapide",
      showBadge: false,
      badge: "",
      bullets: [
        { text: "Produit vérifié par {{store}}" },
        { text: "Paiement à la livraison possible" },
        { text: "Livraison rapide et suivie" },
        { text: "Assistance sur WhatsApp" },
      ],
      showGift: false,
      giftTitle: "",
      giftText: "",
      giftImage: "",
      showTiers: false,
      tiers: [],
      images: [],
      showPayments: false,
      payments: [
        { label: "Mastercard" },
        { label: "Amex" },
        { label: "Apple Pay" },
        { label: "G Pay" },
        { label: "Shop" },
        { label: "Discover" },
        { label: "Visa" },
      ],
      showGuarantee: true,
      guaranteeTitle: "Commande protégée",
      guaranteeText: "Votre paiement est sécurisé et votre commande suivie jusqu'à la livraison.",
      guaranteeIcon: "shield",
      guaranteeIconColor: "",
      guaranteeIconBg: "",
      guaranteeBg: "",
      guaranteeBorderColor: "",
      guaranteePayments: [{ label: "Visa" }, { label: "Mastercard" }],
      guaranteeItems: [
        { label: "Livraison suivie", icon: "truck" },
        { label: "Paiement sécurisé", icon: "lock" },
        { label: "Retour possible", icon: "undo" },
      ],
      showFaq: true,
      faqTitle: "Questions fréquentes",
      faqItems: [
        {
          question: "Quels sont les délais de livraison ?",
          answer: "Nous livrons rapidement et vous recevez un suivi de votre commande.",
        },
        {
          question: "Comment puis-je payer ?",
          answer: "Paiement à la livraison ou Mobile Money, selon votre zone.",
        },
      ],
    },
  },
  usp: {
    type: "usp",
    label: "Argument visuel",
    icon: SlidersHorizontal,
    component: UspSection,
    schema: [
      { key: "eyebrow", label: "Sur-titre", type: "text" },
      { key: "title", label: "Titre", type: "text" },
      { key: "subtitle", label: "Sous-titre", type: "textarea" },
      { key: "image", label: "Image", type: "image" },
      textList("pills", "Badges", true),
      { key: "ctaLabel", label: "Bouton", type: "text" },
      { key: "ctaPath", label: "Lien du bouton", type: "text" },
    ],
    defaults: {
      eyebrow: "Pourquoi {{store}}",
      title: "Une boutique en qui vous pouvez avoir confiance",
      subtitle:
        "Des produits vérifiés, une commande simple et un service client qui répond vraiment.",
      image: "",
      pills: [
        { text: "Produits vérifiés" },
        { text: "Livraison rapide" },
        { text: "Paiement sécurisé" },
        { text: "Support WhatsApp" },
      ],
      ctaLabel: "Voir les produits",
      ctaPath: "/produit",
    },
  },
  benefits: {
    type: "benefits",
    label: "Avantages",
    icon: BadgeCheck,
    component: BenefitsSection,
    schema: [
      { key: "title", label: "Titre", type: "text" },
      { key: "subtitle", label: "Sous-titre", type: "textarea" },
      { key: "image", label: "Image", type: "image" },
      {
        key: "items",
        label: "Avantages",
        type: "list",
        itemFields: [
          { key: "title", label: "Titre", type: "text" },
          { key: "text", label: "Description", type: "textarea" },
          { key: "icon", label: "Icône", type: "icon" },
        ],
        itemLabelKey: "title",
      },
    ],
    defaults: {
      title: "Pourquoi commander chez {{store}}",
      subtitle: "Nos engagements sur chaque commande.",
      image: "",
      items: [
        {
          title: "Livraison rapide",
          text: "Expédition dès la confirmation de votre commande.",
        },
        {
          title: "Paiement sécurisé",
          text: "Mobile Money, carte ou paiement à la livraison.",
        },
        {
          title: "Produits vérifiés",
          text: "Chaque article est contrôlé avant l'envoi.",
        },
        {
          title: "Service client",
          text: "Écrivez-nous sur WhatsApp, nous répondons vite.",
        },
      ],
    },
  },
  marquee: {
    type: "marquee",
    label: "Bandeau défilant",
    icon: AlignLeft,
    component: MarqueeSection,
    schema: [textList("items", "Éléments")],
    defaults: {
      items: [
        { text: "Livraison rapide" },
        { text: "Paiement sécurisé" },
        { text: "Service client réactif" },
      ],
    },
  },
  howto: {
    type: "howto",
    label: "Mode d'emploi",
    icon: LayoutTemplate,
    component: HowToSection,
    schema: [
      { key: "eyebrow", label: "Sur-titre", type: "text" },
      { key: "title", label: "Titre", type: "text" },
      { key: "subtitle", label: "Sous-titre", type: "text" },
      {
        key: "steps",
        label: "Étapes",
        type: "list",
        itemFields: [
          { key: "title", label: "Titre", type: "text" },
          { key: "text", label: "Description", type: "textarea" },
          { key: "image", label: "Image", type: "image" },
        ],
        itemLabelKey: "title",
      },
      { key: "sectionBg", label: "Fond de la section", type: "color", group: "Style" },
      { key: "cardBg", label: "Fond des cartes", type: "color", group: "Style" },
      {
        key: "cardBorderWidth",
        label: "Épaisseur bordure",
        type: "range",
        group: "Style",
        min: 0,
        max: 12,
        unit: "px",
      },
      { key: "cardBorderColor", label: "Couleur de la bordure", type: "color", group: "Style" },
      { key: "numberBg", label: "Fond du numéro", type: "color", group: "Style" },
      { key: "numberColor", label: "Couleur du numéro", type: "color", group: "Style" },
    ],
    defaults: {
      eyebrow: "Mode d'emploi",
      title: "Commander en 3 étapes",
      subtitle: "Simple, rapide et sécurisé.",
      sectionBg: "",
      cardBg: "#ffffff",
      cardBorderWidth: 1,
      cardBorderColor: "#f7c9d6",
      numberBg: "#ffffff",
      numberColor: "#e8688a",

      steps: [
        {
          title: "Choisissez votre produit",
          text: "Parcourez le catalogue et ajoutez au panier.",
          image: "",
        },
        {
          title: "Remplissez le formulaire",
          text: "Nom, téléphone et adresse de livraison.",
          image: "",
        },
        {
          title: "Recevez et payez",
          text: "Nous vous livrons et vous payez à la réception.",
          image: "",
        },
      ],
    },
  },
  stats: {
    type: "stats",
    label: "Chiffres clés",
    icon: Gauge,
    component: StatsSection,
    schema: [
      { key: "eyebrow", label: "Sur-titre", type: "text" },
      { key: "title", label: "Titre", type: "text" },
      { key: "subtitle", label: "Sous-titre", type: "textarea" },
      {
        key: "items",
        label: "Statistiques",
        type: "list",
        itemFields: [
          { key: "value", label: "Valeur", type: "text" },
          { key: "label", label: "Libellé", type: "text" },
          { key: "text", label: "Description", type: "text" },
        ],
        itemLabelKey: "value",
      },
    ],
    defaults: {
      eyebrow: "Résultats",
      title: "{{store}} en quelques chiffres",
      subtitle: "Modifiez ces chiffres depuis l'éditeur.",
      items: [
        { value: "", label: "Commandes livrées", text: "" },
        { value: "", label: "Clients satisfaits", text: "" },
        { value: "", label: "Délai de livraison", text: "" },
      ],
    },
  },
  beforeAfter: {
    type: "beforeAfter",
    label: "Avant / Après",
    icon: GitCompareArrows,
    component: BeforeAfterSection,
    schema: [
      { key: "title", label: "Titre", type: "text" },
      { key: "subtitle", label: "Sous-titre", type: "textarea" },
      { key: "beforeImage", label: "Image avant", type: "image" },
      { key: "beforeLabel", label: "Libellé avant", type: "text" },
      { key: "afterImage", label: "Image après", type: "image" },
      { key: "afterLabel", label: "Libellé après", type: "text" },
    ],
    defaults: {
      title: "Avant / Après",
      subtitle: "Ajoutez vos deux images pour montrer le résultat.",
      beforeImage: "",
      beforeLabel: "Avant",
      afterImage: "",
      afterLabel: "Après",
    },
  },
  comparison: {
    type: "comparison",
    label: "Tableau comparatif",
    icon: GitCompareArrows,
    component: ComparisonSection,
    schema: [
      { key: "title", label: "Titre", type: "text" },
      { key: "subtitle", label: "Sous-titre", type: "textarea" },
      { key: "usLabel", label: "Colonne 1 — nom", type: "text" },
      { key: "usImage", label: "Colonne 1 — image", type: "image" },
      { key: "themLabel", label: "Colonne 2 — nom", type: "text" },
      { key: "themImage", label: "Colonne 2 — image", type: "image" },
      { key: "themGrayscale", label: "Image concurrent en noir & blanc", type: "switch" },
      {
        key: "rows",
        label: "Critères",
        type: "list",
        itemFields: [
          { key: "label", label: "Critère", type: "text" },
          { key: "usValue", label: "Colonne 1 : check / cross / texte", type: "text" },
          { key: "themValue", label: "Colonne 2 : check / cross / texte", type: "text" },
        ],
        itemLabelKey: "label",
      },
      { key: "checkIcon", label: "Icône « validé »", type: "icon", group: "Icônes" },
      { key: "crossIcon", label: "Icône « non »", type: "icon", group: "Icônes" },
      { key: "checkBg", label: "Fond icône validée", type: "color", group: "Icônes" },
      { key: "checkColor", label: "Couleur icône validée", type: "color", group: "Icônes" },
      { key: "crossBg", label: "Fond icône croix", type: "color", group: "Icônes" },
      { key: "crossColor", label: "Couleur icône croix", type: "color", group: "Icônes" },
      { key: "sectionBg", label: "Fond de la section", type: "color", group: "Icônes" },
    ],
    defaults: {
      title: "{{store}} vs. les autres",
      subtitle: "Ce que vous gagnez en commandant chez nous.",
      usLabel: "{{store}}",
      usImage: "",
      themLabel: "Ailleurs",
      themImage: "",
      themGrayscale: true,
      checkIcon: "check",
      crossIcon: "",
      checkBg: "#e8688a",
      checkColor: "#ffffff",
      crossBg: "#f1f1f1",
      crossColor: "#8a8a8a",
      sectionBg: "",
      rows: [
        { label: "Paiement à la livraison", usValue: "check", themValue: "cross" },
        { label: "Produits vérifiés", usValue: "check", themValue: "cross" },
        { label: "Support WhatsApp", usValue: "check", themValue: "cross" },
        { label: "Livraison suivie", usValue: "check", themValue: "cross" },
      ],
    },
  },
  reviews: {
    type: "reviews",
    label: "Avis clients",
    icon: MessageSquareQuote,
    component: ReviewsSection,
    schema: [
      { key: "eyebrow", label: "Sur-titre", type: "text" },
      { key: "title", label: "Titre", type: "text" },
      { key: "verifiedLabel", label: "Badge acheteuse", type: "text" },
      {
        key: "items",
        label: "Avis",
        type: "list",
        itemFields: [
          { key: "author", label: "Autrice", type: "text" },
          { key: "text", label: "Avis", type: "textarea" },
          { key: "image", label: "Photo", type: "image" },
        ],
        itemLabelKey: "author",
      },
      ...trustFields,
    ],
    defaults: {
      ...trustDefaults,
      eyebrow: "Avis clients",
      title: "Ils commandent chez {{store}}",
      verifiedLabel: "Client vérifié",
      items: [],
    },
  },
  faq: {
    type: "faq",
    label: "FAQ",
    icon: HelpCircle,
    component: FaqSection,
    schema: [
      { key: "title", label: "Titre", type: "text" },
      { key: "subtitle", label: "Sous-titre", type: "textarea" },
      {
        key: "items",
        label: "Questions",
        type: "list",
        itemFields: [
          { key: "question", label: "Question", type: "text" },
          { key: "answer", label: "Réponse", type: "textarea" },
        ],
        itemLabelKey: "question",
      },
    ],
    defaults: {
      title: "Questions fréquentes",
      subtitle: "Tout ce qu'il faut savoir avant de commander.",
      items: [
        {
          question: "Quels sont les délais de livraison ?",
          answer: "Votre commande est expédiée dès sa confirmation et suivie jusqu'à vous.",
        },
        {
          question: "Comment payer ma commande ?",
          answer: "Mobile Money, carte bancaire ou paiement à la livraison selon votre zone.",
        },
        {
          question: "Comment vous contacter ?",
          answer: "Écrivez-nous sur WhatsApp au {{phone}}, nous répondons rapidement.",
        },
      ],
    },
  },
  guarantee: {
    type: "guarantee",
    label: "Garantie",
    icon: ShieldCheck,
    component: GuaranteeSection,
    schema: [
      { key: "title", label: "Titre", type: "text" },
      { key: "text", label: "Texte", type: "textarea" },
      { key: "image", label: "Image", type: "image" },
      { key: "ctaLabel", label: "Bouton", type: "text" },
      { key: "ctaPath", label: "Lien du bouton", type: "text" },
    ],
    defaults: {
      title: "Commandez en toute confiance",
      text: "Votre commande est protégée : paiement sécurisé, suivi de livraison et service client joignable à tout moment.",
      image: "",
      ctaLabel: "Voir les produits",
      ctaPath: "/produit",
    },
  },
  press: {
    type: "press",
    label: "Vu dans la presse",
    icon: Newspaper,
    component: PressSection,
    schema: [{ key: "title", label: "Titre", type: "text" }, textList("items", "Médias")],
    defaults: {
      title: "Ils parlent de nous",
      items: [],
    },
  },
  cta: {
    type: "cta",
    label: "Appel à l'action",
    icon: MousePointerClick,
    component: CtaSection,
    schema: [
      { key: "title", label: "Titre", type: "text" },
      { key: "subtitle", label: "Sous-titre", type: "textarea" },
      textList("bullets", "Points forts", true),
      { key: "ctaLabel", label: "Bouton", type: "text" },
      { key: "ctaPath", label: "Lien du bouton", type: "text" },
      { key: "note", label: "Note", type: "text" },
      { key: "image", label: "Image", type: "image" },
    ],
    defaults: {
      title: "Une question avant de commander ?",
      subtitle: "Notre équipe vous répond sur WhatsApp au {{phone}}.",
      bullets: [
        { text: "Réponse rapide" },
        { text: "Paiement sécurisé" },
        { text: "Livraison suivie" },
      ],
      ctaLabel: "Écrire sur WhatsApp",
      ctaPath: "/contact",
      note: "Paiement sécurisé · Livraison suivie",
      image: "",
    },
  },
  social: {
    type: "social",
    label: "Preuve sociale (photos)",
    icon: Images,
    component: SocialSection,
    schema: [
      { key: "title", label: "Titre", type: "text" },
      { key: "handle", label: "Compte Instagram", type: "text" },
      {
        key: "images",
        label: "Photos clientes",
        type: "list",
        itemFields: [{ key: "url", label: "Image", type: "image" }],
        itemLabelKey: "url",
      },
    ],
    defaults: {
      title: "Nos clients en parlent",
      handle: "{{instagram}}",
      images: [],
    },
  },
  contact: {
    type: "contact",
    label: "Contact",
    icon: Contact,
    component: ContactSection,
    schema: [
      { key: "eyebrow", label: "Sur-titre", type: "text" },
      { key: "title", label: "Titre", type: "text" },
      { key: "subtitle", label: "Sous-titre", type: "textarea" },
      { key: "email", label: "E-mail", type: "text" },
      { key: "phone", label: "Téléphone", type: "text" },
      { key: "address", label: "Adresse", type: "text" },
      { key: "hours", label: "Horaires", type: "text" },
      { key: "nameLabel", label: "Champ nom", type: "text" },
      { key: "emailLabel", label: "Champ e-mail", type: "text" },
      { key: "messageLabel", label: "Champ message", type: "text" },
      { key: "submitLabel", label: "Bouton d'envoi", type: "text" },
      { key: "successText", label: "Message de confirmation", type: "text" },
    ],
    defaults: {
      eyebrow: "Service client",
      title: "Une question ? Écrivez-nous",
      subtitle: "Notre équipe vous répond en moins de 24 h, du lundi au samedi.",
      email: "{{email}}",
      phone: "{{phone}}",
      address: "{{address}}",
      hours: "Lun – Sam · 9 h à 19 h",
      nameLabel: "Nom",
      emailLabel: "E-mail",
      messageLabel: "Message",
      submitLabel: "Envoyer le message",
      successText: "Merci ! Nous répondons sous 24 h.",
    },
  },
  waves: {
    type: "waves",
    label: "Vagues (séparateur)",
    icon: Waves,
    component: WavesSection,
    schema: [
      { key: "waveColor", label: "Couleur de la vague", type: "color" },
      {
        key: "waveHeight",
        label: "Hauteur de la vague",
        type: "range",
        min: 20,
        max: 260,
        unit: "px",
      },
      { key: "animated", label: "Animer la vague", type: "switch" },
      { key: "flip", label: "Inverser la vague (à l'envers)", type: "switch" },
      { key: "speed", label: "Durée de l'animation", type: "range", min: 4, max: 40, unit: "s" },
    ],
    defaults: {
      waveColor: "#f7c9d6",
      waveHeight: 90,
      animated: true,
      flip: false,
      speed: 14,
    },
  },
  divider: {
    type: "divider",
    label: "Diviseur (ligne)",
    icon: Minus,
    component: DividerSection,
    schema: [
      { key: "lineColor", label: "Couleur de la ligne", type: "color" },
      { key: "thickness", label: "Épaisseur", type: "range", min: 1, max: 24, unit: "px" },
      { key: "widthPercent", label: "Longueur", type: "range", min: 10, max: 100, unit: "%" },
      {
        key: "align",
        label: "Alignement",
        type: "select",
        options: [
          { value: "left", label: "Gauche" },
          { value: "center", label: "Centré" },
          { value: "right", label: "Droite" },
        ],
      },
      {
        key: "lineStyle",
        label: "Style du trait",
        type: "select",
        options: [
          { value: "solid", label: "Plein" },
          { value: "dashed", label: "Tirets" },
          { value: "dotted", label: "Pointillés" },
        ],
      },
      { key: "spaceTop", label: "Espace au-dessus", type: "range", min: 0, max: 160, unit: "px" },
      {
        key: "spaceBottom",
        label: "Espace en dessous",
        type: "range",
        min: 0,
        max: 160,
        unit: "px",
      },
    ],
    defaults: {
      lineColor: "#f7c9d6",
      thickness: 1,
      widthPercent: 100,
      align: "center",
      lineStyle: "solid",
      spaceTop: 32,
      spaceBottom: 32,
    },
  },
  footer: {
    type: "footer",
    label: "Pied de page",
    icon: Copyright,
    unique: true,
    chrome: true,
    component: FooterSection,
    schema: [
      { key: "brand", label: "Nom de la marque", type: "text" },
      { key: "about", label: "Description", type: "textarea" },
      { key: "navTitle", label: "Titre navigation", type: "text" },
      linkList("navLinks", "Liens de navigation"),
      { key: "legalTitle", label: "Titre informations", type: "text" },
      {
        key: "links",
        label: "Liens juridiques",
        type: "list",
        itemFields: [{ key: "label", label: "Libellé", type: "text" }],
        itemLabelKey: "label",
      },
      { key: "showNewsletter", label: "Afficher la newsletter", type: "switch" },
      { key: "newsletterTitle", label: "Titre newsletter", type: "text" },
      { key: "newsletterText", label: "Texte newsletter", type: "textarea" },
      { key: "newsletterPlaceholder", label: "Placeholder e-mail", type: "text" },
      {
        key: "payments",
        label: "Moyens de paiement",
        type: "list",
        itemFields: [{ key: "label", label: "Libellé", type: "text" }],
        itemLabelKey: "label",
      },
      { key: "copyright", label: "Copyright", type: "text" },
    ],
    defaults: {
      brand: "{{store}}",
      about: "{{description}}",
      navTitle: "Navigation",
      navLinks: [
        { label: "Accueil", path: "/" },
        { label: "Nos produits", path: "/produit" },
        { label: "Contact", path: "/contact" },
      ],
      legalTitle: "Informations",
      links: [
        { label: "Conditions générales" },
        { label: "Politique de confidentialité" },
        { label: "Mentions légales" },
      ],
      showNewsletter: false,
      newsletterTitle: "Newsletter",
      newsletterText: "Recevez nos nouveautés et nos offres en avant-première.",
      newsletterPlaceholder: "Votre e-mail",
      payments: [{ label: "Visa" }, { label: "Mastercard" }],
      copyright: "© {{store}} — Tous droits réservés.",
    },
  },
};

/* ------------------------------------------------------------------------- *
 * Réglages d'apparence disponibles sur TOUTES les sections
 * ------------------------------------------------------------------------- */

const appearanceFields: Field[] = [
  { key: "sectionBg", label: "Couleur de fond", type: "color", group: "Apparence" },
  { key: "textColor", label: "Couleur du texte", type: "color", group: "Apparence" },
  { key: "headingColor", label: "Couleur des titres", type: "color", group: "Apparence" },
  {
    key: "accentColor",
    label: "Couleur d'accent (icônes, badges)",
    type: "color",
    group: "Apparence",
  },
  { key: "softColor", label: "Accent clair", type: "color", group: "Apparence" },
  { key: "paleColor", label: "Fond pastel", type: "color", group: "Apparence" },
  { key: "iconColor", label: "Couleur des icônes", type: "color", group: "Apparence" },
  { key: "iconBg", label: "Fond des icônes", type: "color", group: "Apparence" },
];

/** Espacement vertical (curseurs) disponible sur toutes les sections */
const spacingFields: Field[] = [
  {
    key: "paddingTop",
    label: "Haut",
    type: "range",
    group: "Espacement",
    min: 0,
    max: 200,
    unit: "px",
  },
  {
    key: "paddingBottom",
    label: "Bas",
    type: "range",
    group: "Espacement",
    min: 0,
    max: 200,
    unit: "px",
  },
];

const buttonFields: Field[] = [
  { key: "btnBg", label: "Fond du bouton", type: "color", group: "Bouton" },
  { key: "btnColor", label: "Texte du bouton", type: "color", group: "Bouton" },
  { key: "btnIcon", label: "Icône du bouton", type: "icon", group: "Bouton" },
];

const withButtons: SectionType[] = [
  "header",
  "homeHero",
  "hero",
  "usp",
  "guarantee",
  "cta",
  "contact",
  "footer",
];

const appearanceDefaults: Settings = {
  ...Object.fromEntries([...appearanceFields, ...buttonFields].map((f) => [f.key, ""])),
  paddingTop: 0,
  paddingBottom: 0,
};

for (const def of Object.values(sectionDefinitions)) {
  const extra = [
    ...appearanceFields,
    ...(withButtons.includes(def.type) ? buttonFields : []),
    ...spacingFields,
  ];
  const existing = new Set(def.schema.map((field) => field.key));
  def.schema = [...def.schema, ...extra.filter((field) => !existing.has(field.key))];
  def.defaults = {
    ...Object.fromEntries(
      Object.entries(appearanceDefaults).filter(([key]) => !(key in def.defaults)),
    ),
    ...def.defaults,
  };
}

export const sectionLibrary = Object.values(sectionDefinitions);

export const getDefinition = (type: SectionType) => sectionDefinitions[type];

export const StarPreviewIcon = Star;
