/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AideRouteImport } from './routes/aide'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoPreviewRouteImport } from './routes/logo-preview'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RejoindreRouteImport } from './routes/rejoindre'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TendancesRouteImport } from './routes/tendances'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as TendancesIndexRouteImport } from './routes/tendances.index'
import { Route as TendancesIdRouteImport } from './routes/tendances.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAbonnementsRouteImport } from './routes/_authenticated/admin/abonnements'
import { Route as AuthenticatedAdminAdministrateursRouteImport } from './routes/_authenticated/admin/administrateurs'
import { Route as AuthenticatedAdminBoutiquesRouteImport } from './routes/_authenticated/admin/boutiques'
import { Route as AuthenticatedAdminCommandesRouteImport } from './routes/_authenticated/admin/commandes'
import { Route as AuthenticatedAdminComptesRouteImport } from './routes/_authenticated/admin/comptes'
import { Route as AuthenticatedAdminJournalRouteImport } from './routes/_authenticated/admin/journal'
import { Route as AuthenticatedAdminModelesIaRouteImport } from './routes/_authenticated/admin/modeles-ia'
import { Route as AuthenticatedAdminPromosRouteImport } from './routes/_authenticated/admin/promos'
import { Route as AuthenticatedAdminRetraitsRouteImport } from './routes/_authenticated/admin/retraits'
import { Route as AuthenticatedAdminTendancesRouteImport } from './routes/_authenticated/admin/tendances'
import { Route as AuthenticatedAdminTraficRouteImport } from './routes/_authenticated/admin/trafic'
import { Route as AuthenticatedAdminVerificationRouteImport } from './routes/_authenticated/admin/verification'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardAnalysesRouteImport } from './routes/_authenticated/dashboard/analyses'
import { Route as AuthenticatedDashboardBoutiqueRouteImport } from './routes/_authenticated/dashboard/boutique'
import { Route as AuthenticatedDashboardCollectionsRouteImport } from './routes/_authenticated/dashboard/collections'
import { Route as AuthenticatedDashboardEditeurRouteImport } from './routes/_authenticated/dashboard/editeur'
import { Route as AuthenticatedDashboardEquipeRouteImport } from './routes/_authenticated/dashboard/equipe'
import { Route as AuthenticatedDashboardParametresRouteImport } from './routes/_authenticated/dashboard/parametres'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'
import { Route as SHandleIndexRouteImport } from './routes/s.$handle.index'
import { Route as SHandleCommandeRouteImport } from './routes/s.$handle.commande'
import { Route as SHandleContactRouteImport } from './routes/s.$handle.contact'
import { Route as SHandleProduitsRouteImport } from './routes/s.$handle.produits'
import { Route as AuthenticatedDashboardClientsIndexRouteImport } from './routes/_authenticated/dashboard/clients.index'
import { Route as AuthenticatedDashboardClientsSegmentsRouteImport } from './routes/_authenticated/dashboard/clients.segments'
import { Route as AuthenticatedDashboardCommandesIndexRouteImport } from './routes/_authenticated/dashboard/commandes.index'
import { Route as AuthenticatedDashboardCommandesPaniersRouteImport } from './routes/_authenticated/dashboard/commandes.paniers'
import { Route as AuthenticatedDashboardDecouverteIndexRouteImport } from './routes/_authenticated/dashboard/decouverte.index'
import { Route as AuthenticatedDashboardDecouverteBoutiquesRouteImport } from './routes/_authenticated/dashboard/decouverte.boutiques'
import { Route as AuthenticatedDashboardDecouverteFavorisRouteImport } from './routes/_authenticated/dashboard/decouverte.favoris'
import { Route as AuthenticatedDashboardDecouverteProduitsRouteImport } from './routes/_authenticated/dashboard/decouverte.produits'
import { Route as AuthenticatedDashboardDecouvertePublicitesRouteImport } from './routes/_authenticated/dashboard/decouverte.publicites'
import { Route as AuthenticatedDashboardMarketingIndexRouteImport } from './routes/_authenticated/dashboard/marketing.index'
import { Route as AuthenticatedDashboardProduitsIndexRouteImport } from './routes/_authenticated/dashboard/produits.index'
import { Route as AuthenticatedDashboardProduitsIaRouteImport } from './routes/_authenticated/dashboard/produits.ia'
import { Route as AuthenticatedDashboardProduitsNouveauRouteImport } from './routes/_authenticated/dashboard/produits.nouveau'
import { Route as ApiPublicBillingLigdicashRouteImport } from './routes/api/public/billing.ligdicash'
import { Route as ApiPublicBillingPawapayRouteImport } from './routes/api/public/billing.pawapay'
import { Route as ApiPublicCronDecouverteRouteImport } from './routes/api/public/cron.decouverte'
import { Route as ApiPublicCronRelancesRouteImport } from './routes/api/public/cron.relances'
import { Route as SHandleProduitIndexRouteImport } from './routes/s.$handle.produit.index'
import { Route as SHandleProduitProductIdRouteImport } from './routes/s.$handle.produit.$productId'
import { Route as AuthenticatedDashboardMarketingEmailsIdRouteImport } from './routes/_authenticated/dashboard/marketing.emails.$id'
import { Route as AuthenticatedDashboardMarketingOffresNouveauRouteImport } from './routes/_authenticated/dashboard/marketing.offres.nouveau'
import { Route as ApiPublicECRidRouteImport } from './routes/api/public/e.c.$rid'
import { Route as ApiPublicEORidRouteImport } from './routes/api/public/e.o.$rid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoPreviewRoute = LogoPreviewRouteImport.update({
  id: '/logo-preview',
  path: '/logo-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RejoindreRoute = RejoindreRouteImport.update({
  id: '/rejoindre',
  path: '/rejoindre',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TendancesRoute = TendancesRouteImport.update({
  id: '/tendances',
  path: '/tendances',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TendancesIndexRoute = TendancesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TendancesRoute,
} as any)
const TendancesIdRoute = TendancesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TendancesRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAbonnementsRoute =
  AuthenticatedAdminAbonnementsRouteImport.update({
    id: '/abonnements',
    path: '/abonnements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdministrateursRoute =
  AuthenticatedAdminAdministrateursRouteImport.update({
    id: '/administrateurs',
    path: '/administrateurs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBoutiquesRoute =
  AuthenticatedAdminBoutiquesRouteImport.update({
    id: '/boutiques',
    path: '/boutiques',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommandesRoute =
  AuthenticatedAdminCommandesRouteImport.update({
    id: '/commandes',
    path: '/commandes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminComptesRoute =
  AuthenticatedAdminComptesRouteImport.update({
    id: '/comptes',
    path: '/comptes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminJournalRoute =
  AuthenticatedAdminJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModelesIaRoute =
  AuthenticatedAdminModelesIaRouteImport.update({
    id: '/modeles-ia',
    path: '/modeles-ia',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPromosRoute =
  AuthenticatedAdminPromosRouteImport.update({
    id: '/promos',
    path: '/promos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRetraitsRoute =
  AuthenticatedAdminRetraitsRouteImport.update({
    id: '/retraits',
    path: '/retraits',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTendancesRoute =
  AuthenticatedAdminTendancesRouteImport.update({
    id: '/tendances',
    path: '/tendances',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTraficRoute =
  AuthenticatedAdminTraficRouteImport.update({
    id: '/trafic',
    path: '/trafic',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVerificationRoute =
  AuthenticatedAdminVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAnalysesRoute =
  AuthenticatedDashboardAnalysesRouteImport.update({
    id: '/dashboard/analyses',
    path: '/dashboard/analyses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardBoutiqueRoute =
  AuthenticatedDashboardBoutiqueRouteImport.update({
    id: '/dashboard/boutique',
    path: '/dashboard/boutique',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCollectionsRoute =
  AuthenticatedDashboardCollectionsRouteImport.update({
    id: '/dashboard/collections',
    path: '/dashboard/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardEditeurRoute =
  AuthenticatedDashboardEditeurRouteImport.update({
    id: '/dashboard/editeur',
    path: '/dashboard/editeur',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardEquipeRoute =
  AuthenticatedDashboardEquipeRouteImport.update({
    id: '/dashboard/equipe',
    path: '/dashboard/equipe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardParametresRoute =
  AuthenticatedDashboardParametresRouteImport.update({
    id: '/dashboard/parametres',
    path: '/dashboard/parametres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const SHandleIndexRoute = SHandleIndexRouteImport.update({
  id: '/s/$handle/',
  path: '/s/$handle/',
  getParentRoute: () => rootRouteImport,
} as any)
const SHandleCommandeRoute = SHandleCommandeRouteImport.update({
  id: '/s/$handle/commande',
  path: '/s/$handle/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const SHandleContactRoute = SHandleContactRouteImport.update({
  id: '/s/$handle/contact',
  path: '/s/$handle/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SHandleProduitsRoute = SHandleProduitsRouteImport.update({
  id: '/s/$handle/produits',
  path: '/s/$handle/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardClientsIndexRoute =
  AuthenticatedDashboardClientsIndexRouteImport.update({
    id: '/dashboard/clients/',
    path: '/dashboard/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardClientsSegmentsRoute =
  AuthenticatedDashboardClientsSegmentsRouteImport.update({
    id: '/dashboard/clients/segments',
    path: '/dashboard/clients/segments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCommandesIndexRoute =
  AuthenticatedDashboardCommandesIndexRouteImport.update({
    id: '/dashboard/commandes/',
    path: '/dashboard/commandes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCommandesPaniersRoute =
  AuthenticatedDashboardCommandesPaniersRouteImport.update({
    id: '/dashboard/commandes/paniers',
    path: '/dashboard/commandes/paniers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDecouverteIndexRoute =
  AuthenticatedDashboardDecouverteIndexRouteImport.update({
    id: '/dashboard/decouverte/',
    path: '/dashboard/decouverte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDecouverteBoutiquesRoute =
  AuthenticatedDashboardDecouverteBoutiquesRouteImport.update({
    id: '/dashboard/decouverte/boutiques',
    path: '/dashboard/decouverte/boutiques',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDecouverteFavorisRoute =
  AuthenticatedDashboardDecouverteFavorisRouteImport.update({
    id: '/dashboard/decouverte/favoris',
    path: '/dashboard/decouverte/favoris',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDecouverteProduitsRoute =
  AuthenticatedDashboardDecouverteProduitsRouteImport.update({
    id: '/dashboard/decouverte/produits',
    path: '/dashboard/decouverte/produits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDecouvertePublicitesRoute =
  AuthenticatedDashboardDecouvertePublicitesRouteImport.update({
    id: '/dashboard/decouverte/publicites',
    path: '/dashboard/decouverte/publicites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardMarketingIndexRoute =
  AuthenticatedDashboardMarketingIndexRouteImport.update({
    id: '/dashboard/marketing/',
    path: '/dashboard/marketing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProduitsIndexRoute =
  AuthenticatedDashboardProduitsIndexRouteImport.update({
    id: '/dashboard/produits/',
    path: '/dashboard/produits/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProduitsIaRoute =
  AuthenticatedDashboardProduitsIaRouteImport.update({
    id: '/dashboard/produits/ia',
    path: '/dashboard/produits/ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProduitsNouveauRoute =
  AuthenticatedDashboardProduitsNouveauRouteImport.update({
    id: '/dashboard/produits/nouveau',
    path: '/dashboard/produits/nouveau',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBillingLigdicashRoute =
  ApiPublicBillingLigdicashRouteImport.update({
    id: '/api/public/billing/ligdicash',
    path: '/api/public/billing/ligdicash',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingPawapayRoute = ApiPublicBillingPawapayRouteImport.update({
  id: '/api/public/billing/pawapay',
  path: '/api/public/billing/pawapay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDecouverteRoute = ApiPublicCronDecouverteRouteImport.update({
  id: '/api/public/cron/decouverte',
  path: '/api/public/cron/decouverte',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRelancesRoute = ApiPublicCronRelancesRouteImport.update({
  id: '/api/public/cron/relances',
  path: '/api/public/cron/relances',
  getParentRoute: () => rootRouteImport,
} as any)
const SHandleProduitIndexRoute = SHandleProduitIndexRouteImport.update({
  id: '/s/$handle/produit/',
  path: '/s/$handle/produit/',
  getParentRoute: () => rootRouteImport,
} as any)
const SHandleProduitProductIdRoute = SHandleProduitProductIdRouteImport.update({
  id: '/s/$handle/produit/$productId',
  path: '/s/$handle/produit/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardMarketingEmailsIdRoute =
  AuthenticatedDashboardMarketingEmailsIdRouteImport.update({
    id: '/dashboard/marketing/emails/$id',
    path: '/dashboard/marketing/emails/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardMarketingOffresNouveauRoute =
  AuthenticatedDashboardMarketingOffresNouveauRouteImport.update({
    id: '/dashboard/marketing/offres/nouveau',
    path: '/dashboard/marketing/offres/nouveau',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicECRidRoute = ApiPublicECRidRouteImport.update({
  id: '/api/public/e/c/$rid',
  path: '/api/public/e/c/$rid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEORidRoute = ApiPublicEORidRouteImport.update({
  id: '/api/public/e/o/$rid',
  path: '/api/public/e/o/$rid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aide': typeof AideRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/logo-preview': typeof LogoPreviewRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/onboarding': typeof OnboardingRoute
  '/rejoindre': typeof RejoindreRoute
  '/signup': typeof SignupRoute
  '/tendances': typeof TendancesRouteWithChildren
  '/verification': typeof VerificationRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/tendances/$id': typeof TendancesIdRoute
  '/tendances/': typeof TendancesIndexRoute
  '/admin/abonnements': typeof AuthenticatedAdminAbonnementsRoute
  '/admin/administrateurs': typeof AuthenticatedAdminAdministrateursRoute
  '/admin/boutiques': typeof AuthenticatedAdminBoutiquesRoute
  '/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/admin/comptes': typeof AuthenticatedAdminComptesRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/modeles-ia': typeof AuthenticatedAdminModelesIaRoute
  '/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/admin/retraits': typeof AuthenticatedAdminRetraitsRoute
  '/admin/tendances': typeof AuthenticatedAdminTendancesRoute
  '/admin/trafic': typeof AuthenticatedAdminTraficRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/dashboard/analyses': typeof AuthenticatedDashboardAnalysesRoute
  '/dashboard/boutique': typeof AuthenticatedDashboardBoutiqueRoute
  '/dashboard/collections': typeof AuthenticatedDashboardCollectionsRoute
  '/dashboard/editeur': typeof AuthenticatedDashboardEditeurRoute
  '/dashboard/equipe': typeof AuthenticatedDashboardEquipeRoute
  '/dashboard/parametres': typeof AuthenticatedDashboardParametresRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/s/$handle/commande': typeof SHandleCommandeRoute
  '/s/$handle/contact': typeof SHandleContactRoute
  '/s/$handle/produits': typeof SHandleProduitsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/s/$handle/': typeof SHandleIndexRoute
  '/dashboard/clients/segments': typeof AuthenticatedDashboardClientsSegmentsRoute
  '/dashboard/commandes/paniers': typeof AuthenticatedDashboardCommandesPaniersRoute
  '/dashboard/decouverte/boutiques': typeof AuthenticatedDashboardDecouverteBoutiquesRoute
  '/dashboard/decouverte/favoris': typeof AuthenticatedDashboardDecouverteFavorisRoute
  '/dashboard/decouverte/produits': typeof AuthenticatedDashboardDecouverteProduitsRoute
  '/dashboard/decouverte/publicites': typeof AuthenticatedDashboardDecouvertePublicitesRoute
  '/dashboard/produits/ia': typeof AuthenticatedDashboardProduitsIaRoute
  '/dashboard/produits/nouveau': typeof AuthenticatedDashboardProduitsNouveauRoute
  '/api/public/billing/ligdicash': typeof ApiPublicBillingLigdicashRoute
  '/api/public/billing/pawapay': typeof ApiPublicBillingPawapayRoute
  '/api/public/cron/decouverte': typeof ApiPublicCronDecouverteRoute
  '/api/public/cron/relances': typeof ApiPublicCronRelancesRoute
  '/s/$handle/produit/$productId': typeof SHandleProduitProductIdRoute
  '/dashboard/clients/': typeof AuthenticatedDashboardClientsIndexRoute
  '/dashboard/commandes/': typeof AuthenticatedDashboardCommandesIndexRoute
  '/dashboard/decouverte/': typeof AuthenticatedDashboardDecouverteIndexRoute
  '/dashboard/marketing/': typeof AuthenticatedDashboardMarketingIndexRoute
  '/dashboard/produits/': typeof AuthenticatedDashboardProduitsIndexRoute
  '/s/$handle/produit/': typeof SHandleProduitIndexRoute
  '/dashboard/marketing/emails/$id': typeof AuthenticatedDashboardMarketingEmailsIdRoute
  '/dashboard/marketing/offres/nouveau': typeof AuthenticatedDashboardMarketingOffresNouveauRoute
  '/api/public/e/c/$rid': typeof ApiPublicECRidRoute
  '/api/public/e/o/$rid': typeof ApiPublicEORidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aide': typeof AideRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/logo-preview': typeof LogoPreviewRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/onboarding': typeof OnboardingRoute
  '/rejoindre': typeof RejoindreRoute
  '/signup': typeof SignupRoute
  '/verification': typeof VerificationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/tendances/$id': typeof TendancesIdRoute
  '/tendances': typeof TendancesIndexRoute
  '/admin/abonnements': typeof AuthenticatedAdminAbonnementsRoute
  '/admin/administrateurs': typeof AuthenticatedAdminAdministrateursRoute
  '/admin/boutiques': typeof AuthenticatedAdminBoutiquesRoute
  '/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/admin/comptes': typeof AuthenticatedAdminComptesRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/modeles-ia': typeof AuthenticatedAdminModelesIaRoute
  '/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/admin/retraits': typeof AuthenticatedAdminRetraitsRoute
  '/admin/tendances': typeof AuthenticatedAdminTendancesRoute
  '/admin/trafic': typeof AuthenticatedAdminTraficRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/dashboard/analyses': typeof AuthenticatedDashboardAnalysesRoute
  '/dashboard/boutique': typeof AuthenticatedDashboardBoutiqueRoute
  '/dashboard/collections': typeof AuthenticatedDashboardCollectionsRoute
  '/dashboard/editeur': typeof AuthenticatedDashboardEditeurRoute
  '/dashboard/equipe': typeof AuthenticatedDashboardEquipeRoute
  '/dashboard/parametres': typeof AuthenticatedDashboardParametresRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/s/$handle/commande': typeof SHandleCommandeRoute
  '/s/$handle/contact': typeof SHandleContactRoute
  '/s/$handle/produits': typeof SHandleProduitsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/s/$handle': typeof SHandleIndexRoute
  '/dashboard/clients/segments': typeof AuthenticatedDashboardClientsSegmentsRoute
  '/dashboard/commandes/paniers': typeof AuthenticatedDashboardCommandesPaniersRoute
  '/dashboard/decouverte/boutiques': typeof AuthenticatedDashboardDecouverteBoutiquesRoute
  '/dashboard/decouverte/favoris': typeof AuthenticatedDashboardDecouverteFavorisRoute
  '/dashboard/decouverte/produits': typeof AuthenticatedDashboardDecouverteProduitsRoute
  '/dashboard/decouverte/publicites': typeof AuthenticatedDashboardDecouvertePublicitesRoute
  '/dashboard/produits/ia': typeof AuthenticatedDashboardProduitsIaRoute
  '/dashboard/produits/nouveau': typeof AuthenticatedDashboardProduitsNouveauRoute
  '/api/public/billing/ligdicash': typeof ApiPublicBillingLigdicashRoute
  '/api/public/billing/pawapay': typeof ApiPublicBillingPawapayRoute
  '/api/public/cron/decouverte': typeof ApiPublicCronDecouverteRoute
  '/api/public/cron/relances': typeof ApiPublicCronRelancesRoute
  '/s/$handle/produit/$productId': typeof SHandleProduitProductIdRoute
  '/dashboard/clients': typeof AuthenticatedDashboardClientsIndexRoute
  '/dashboard/commandes': typeof AuthenticatedDashboardCommandesIndexRoute
  '/dashboard/decouverte': typeof AuthenticatedDashboardDecouverteIndexRoute
  '/dashboard/marketing': typeof AuthenticatedDashboardMarketingIndexRoute
  '/dashboard/produits': typeof AuthenticatedDashboardProduitsIndexRoute
  '/s/$handle/produit': typeof SHandleProduitIndexRoute
  '/dashboard/marketing/emails/$id': typeof AuthenticatedDashboardMarketingEmailsIdRoute
  '/dashboard/marketing/offres/nouveau': typeof AuthenticatedDashboardMarketingOffresNouveauRoute
  '/api/public/e/c/$rid': typeof ApiPublicECRidRoute
  '/api/public/e/o/$rid': typeof ApiPublicEORidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/aide': typeof AideRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/logo-preview': typeof LogoPreviewRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/onboarding': typeof OnboardingRoute
  '/rejoindre': typeof RejoindreRoute
  '/signup': typeof SignupRoute
  '/tendances': typeof TendancesRouteWithChildren
  '/verification': typeof VerificationRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/tendances/$id': typeof TendancesIdRoute
  '/tendances/': typeof TendancesIndexRoute
  '/_authenticated/admin/abonnements': typeof AuthenticatedAdminAbonnementsRoute
  '/_authenticated/admin/administrateurs': typeof AuthenticatedAdminAdministrateursRoute
  '/_authenticated/admin/boutiques': typeof AuthenticatedAdminBoutiquesRoute
  '/_authenticated/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/_authenticated/admin/comptes': typeof AuthenticatedAdminComptesRoute
  '/_authenticated/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/_authenticated/admin/modeles-ia': typeof AuthenticatedAdminModelesIaRoute
  '/_authenticated/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/_authenticated/admin/retraits': typeof AuthenticatedAdminRetraitsRoute
  '/_authenticated/admin/tendances': typeof AuthenticatedAdminTendancesRoute
  '/_authenticated/admin/trafic': typeof AuthenticatedAdminTraficRoute
  '/_authenticated/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/_authenticated/dashboard/analyses': typeof AuthenticatedDashboardAnalysesRoute
  '/_authenticated/dashboard/boutique': typeof AuthenticatedDashboardBoutiqueRoute
  '/_authenticated/dashboard/collections': typeof AuthenticatedDashboardCollectionsRoute
  '/_authenticated/dashboard/editeur': typeof AuthenticatedDashboardEditeurRoute
  '/_authenticated/dashboard/equipe': typeof AuthenticatedDashboardEquipeRoute
  '/_authenticated/dashboard/parametres': typeof AuthenticatedDashboardParametresRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/s/$handle/commande': typeof SHandleCommandeRoute
  '/s/$handle/contact': typeof SHandleContactRoute
  '/s/$handle/produits': typeof SHandleProduitsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/s/$handle/': typeof SHandleIndexRoute
  '/_authenticated/dashboard/clients/segments': typeof AuthenticatedDashboardClientsSegmentsRoute
  '/_authenticated/dashboard/commandes/paniers': typeof AuthenticatedDashboardCommandesPaniersRoute
  '/_authenticated/dashboard/decouverte/boutiques': typeof AuthenticatedDashboardDecouverteBoutiquesRoute
  '/_authenticated/dashboard/decouverte/favoris': typeof AuthenticatedDashboardDecouverteFavorisRoute
  '/_authenticated/dashboard/decouverte/produits': typeof AuthenticatedDashboardDecouverteProduitsRoute
  '/_authenticated/dashboard/decouverte/publicites': typeof AuthenticatedDashboardDecouvertePublicitesRoute
  '/_authenticated/dashboard/produits/ia': typeof AuthenticatedDashboardProduitsIaRoute
  '/_authenticated/dashboard/produits/nouveau': typeof AuthenticatedDashboardProduitsNouveauRoute
  '/api/public/billing/ligdicash': typeof ApiPublicBillingLigdicashRoute
  '/api/public/billing/pawapay': typeof ApiPublicBillingPawapayRoute
  '/api/public/cron/decouverte': typeof ApiPublicCronDecouverteRoute
  '/api/public/cron/relances': typeof ApiPublicCronRelancesRoute
  '/s/$handle/produit/$productId': typeof SHandleProduitProductIdRoute
  '/_authenticated/dashboard/clients/': typeof AuthenticatedDashboardClientsIndexRoute
  '/_authenticated/dashboard/commandes/': typeof AuthenticatedDashboardCommandesIndexRoute
  '/_authenticated/dashboard/decouverte/': typeof AuthenticatedDashboardDecouverteIndexRoute
  '/_authenticated/dashboard/marketing/': typeof AuthenticatedDashboardMarketingIndexRoute
  '/_authenticated/dashboard/produits/': typeof AuthenticatedDashboardProduitsIndexRoute
  '/s/$handle/produit/': typeof SHandleProduitIndexRoute
  '/_authenticated/dashboard/marketing/emails/$id': typeof AuthenticatedDashboardMarketingEmailsIdRoute
  '/_authenticated/dashboard/marketing/offres/nouveau': typeof AuthenticatedDashboardMarketingOffresNouveauRoute
  '/api/public/e/c/$rid': typeof ApiPublicECRidRoute
  '/api/public/e/o/$rid': typeof ApiPublicEORidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aide'
    | '/confidentialite'
    | '/login'
    | '/logo-preview'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/onboarding'
    | '/rejoindre'
    | '/signup'
    | '/tendances'
    | '/verification'
    | '/admin'
    | '/auth/callback'
    | '/tendances/$id'
    | '/tendances/'
    | '/admin/abonnements'
    | '/admin/administrateurs'
    | '/admin/boutiques'
    | '/admin/commandes'
    | '/admin/comptes'
    | '/admin/journal'
    | '/admin/modeles-ia'
    | '/admin/promos'
    | '/admin/retraits'
    | '/admin/tendances'
    | '/admin/trafic'
    | '/admin/verification'
    | '/dashboard/analyses'
    | '/dashboard/boutique'
    | '/dashboard/collections'
    | '/dashboard/editeur'
    | '/dashboard/equipe'
    | '/dashboard/parametres'
    | '/api/public/whatsapp'
    | '/s/$handle/commande'
    | '/s/$handle/contact'
    | '/s/$handle/produits'
    | '/admin/'
    | '/dashboard/'
    | '/s/$handle/'
    | '/dashboard/clients/segments'
    | '/dashboard/commandes/paniers'
    | '/dashboard/decouverte/boutiques'
    | '/dashboard/decouverte/favoris'
    | '/dashboard/decouverte/produits'
    | '/dashboard/decouverte/publicites'
    | '/dashboard/produits/ia'
    | '/dashboard/produits/nouveau'
    | '/api/public/billing/ligdicash'
    | '/api/public/billing/pawapay'
    | '/api/public/cron/decouverte'
    | '/api/public/cron/relances'
    | '/s/$handle/produit/$productId'
    | '/dashboard/clients/'
    | '/dashboard/commandes/'
    | '/dashboard/decouverte/'
    | '/dashboard/marketing/'
    | '/dashboard/produits/'
    | '/s/$handle/produit/'
    | '/dashboard/marketing/emails/$id'
    | '/dashboard/marketing/offres/nouveau'
    | '/api/public/e/c/$rid'
    | '/api/public/e/o/$rid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aide'
    | '/confidentialite'
    | '/login'
    | '/logo-preview'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/onboarding'
    | '/rejoindre'
    | '/signup'
    | '/verification'
    | '/auth/callback'
    | '/tendances/$id'
    | '/tendances'
    | '/admin/abonnements'
    | '/admin/administrateurs'
    | '/admin/boutiques'
    | '/admin/commandes'
    | '/admin/comptes'
    | '/admin/journal'
    | '/admin/modeles-ia'
    | '/admin/promos'
    | '/admin/retraits'
    | '/admin/tendances'
    | '/admin/trafic'
    | '/admin/verification'
    | '/dashboard/analyses'
    | '/dashboard/boutique'
    | '/dashboard/collections'
    | '/dashboard/editeur'
    | '/dashboard/equipe'
    | '/dashboard/parametres'
    | '/api/public/whatsapp'
    | '/s/$handle/commande'
    | '/s/$handle/contact'
    | '/s/$handle/produits'
    | '/admin'
    | '/dashboard'
    | '/s/$handle'
    | '/dashboard/clients/segments'
    | '/dashboard/commandes/paniers'
    | '/dashboard/decouverte/boutiques'
    | '/dashboard/decouverte/favoris'
    | '/dashboard/decouverte/produits'
    | '/dashboard/decouverte/publicites'
    | '/dashboard/produits/ia'
    | '/dashboard/produits/nouveau'
    | '/api/public/billing/ligdicash'
    | '/api/public/billing/pawapay'
    | '/api/public/cron/decouverte'
    | '/api/public/cron/relances'
    | '/s/$handle/produit/$productId'
    | '/dashboard/clients'
    | '/dashboard/commandes'
    | '/dashboard/decouverte'
    | '/dashboard/marketing'
    | '/dashboard/produits'
    | '/s/$handle/produit'
    | '/dashboard/marketing/emails/$id'
    | '/dashboard/marketing/offres/nouveau'
    | '/api/public/e/c/$rid'
    | '/api/public/e/o/$rid'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/aide'
    | '/confidentialite'
    | '/login'
    | '/logo-preview'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/onboarding'
    | '/rejoindre'
    | '/signup'
    | '/tendances'
    | '/verification'
    | '/_authenticated/admin'
    | '/auth/callback'
    | '/tendances/$id'
    | '/tendances/'
    | '/_authenticated/admin/abonnements'
    | '/_authenticated/admin/administrateurs'
    | '/_authenticated/admin/boutiques'
    | '/_authenticated/admin/commandes'
    | '/_authenticated/admin/comptes'
    | '/_authenticated/admin/journal'
    | '/_authenticated/admin/modeles-ia'
    | '/_authenticated/admin/promos'
    | '/_authenticated/admin/retraits'
    | '/_authenticated/admin/tendances'
    | '/_authenticated/admin/trafic'
    | '/_authenticated/admin/verification'
    | '/_authenticated/dashboard/analyses'
    | '/_authenticated/dashboard/boutique'
    | '/_authenticated/dashboard/collections'
    | '/_authenticated/dashboard/editeur'
    | '/_authenticated/dashboard/equipe'
    | '/_authenticated/dashboard/parametres'
    | '/api/public/whatsapp'
    | '/s/$handle/commande'
    | '/s/$handle/contact'
    | '/s/$handle/produits'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/s/$handle/'
    | '/_authenticated/dashboard/clients/segments'
    | '/_authenticated/dashboard/commandes/paniers'
    | '/_authenticated/dashboard/decouverte/boutiques'
    | '/_authenticated/dashboard/decouverte/favoris'
    | '/_authenticated/dashboard/decouverte/produits'
    | '/_authenticated/dashboard/decouverte/publicites'
    | '/_authenticated/dashboard/produits/ia'
    | '/_authenticated/dashboard/produits/nouveau'
    | '/api/public/billing/ligdicash'
    | '/api/public/billing/pawapay'
    | '/api/public/cron/decouverte'
    | '/api/public/cron/relances'
    | '/s/$handle/produit/$productId'
    | '/_authenticated/dashboard/clients/'
    | '/_authenticated/dashboard/commandes/'
    | '/_authenticated/dashboard/decouverte/'
    | '/_authenticated/dashboard/marketing/'
    | '/_authenticated/dashboard/produits/'
    | '/s/$handle/produit/'
    | '/_authenticated/dashboard/marketing/emails/$id'
    | '/_authenticated/dashboard/marketing/offres/nouveau'
    | '/api/public/e/c/$rid'
    | '/api/public/e/o/$rid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AideRoute: typeof AideRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  LoginRoute: typeof LoginRoute
  LogoPreviewRoute: typeof LogoPreviewRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  OnboardingRoute: typeof OnboardingRoute
  RejoindreRoute: typeof RejoindreRoute
  SignupRoute: typeof SignupRoute
  TendancesRoute: typeof TendancesRouteWithChildren
  VerificationRoute: typeof VerificationRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
  SHandleCommandeRoute: typeof SHandleCommandeRoute
  SHandleContactRoute: typeof SHandleContactRoute
  SHandleProduitsRoute: typeof SHandleProduitsRoute
  SHandleIndexRoute: typeof SHandleIndexRoute
  ApiPublicBillingLigdicashRoute: typeof ApiPublicBillingLigdicashRoute
  ApiPublicBillingPawapayRoute: typeof ApiPublicBillingPawapayRoute
  ApiPublicCronDecouverteRoute: typeof ApiPublicCronDecouverteRoute
  ApiPublicCronRelancesRoute: typeof ApiPublicCronRelancesRoute
  SHandleProduitProductIdRoute: typeof SHandleProduitProductIdRoute
  SHandleProduitIndexRoute: typeof SHandleProduitIndexRoute
  ApiPublicECRidRoute: typeof ApiPublicECRidRoute
  ApiPublicEORidRoute: typeof ApiPublicEORidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-preview': {
      id: '/logo-preview'
      path: '/logo-preview'
      fullPath: '/logo-preview'
      preLoaderRoute: typeof LogoPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejoindre': {
      id: '/rejoindre'
      path: '/rejoindre'
      fullPath: '/rejoindre'
      preLoaderRoute: typeof RejoindreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tendances': {
      id: '/tendances'
      path: '/tendances'
      fullPath: '/tendances'
      preLoaderRoute: typeof TendancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tendances/': {
      id: '/tendances/'
      path: '/'
      fullPath: '/tendances/'
      preLoaderRoute: typeof TendancesIndexRouteImport
      parentRoute: typeof TendancesRoute
    }
    '/tendances/$id': {
      id: '/tendances/$id'
      path: '/$id'
      fullPath: '/tendances/$id'
      preLoaderRoute: typeof TendancesIdRouteImport
      parentRoute: typeof TendancesRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/abonnements': {
      id: '/_authenticated/admin/abonnements'
      path: '/abonnements'
      fullPath: '/admin/abonnements'
      preLoaderRoute: typeof AuthenticatedAdminAbonnementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/administrateurs': {
      id: '/_authenticated/admin/administrateurs'
      path: '/administrateurs'
      fullPath: '/admin/administrateurs'
      preLoaderRoute: typeof AuthenticatedAdminAdministrateursRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/boutiques': {
      id: '/_authenticated/admin/boutiques'
      path: '/boutiques'
      fullPath: '/admin/boutiques'
      preLoaderRoute: typeof AuthenticatedAdminBoutiquesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/commandes': {
      id: '/_authenticated/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AuthenticatedAdminCommandesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/comptes': {
      id: '/_authenticated/admin/comptes'
      path: '/comptes'
      fullPath: '/admin/comptes'
      preLoaderRoute: typeof AuthenticatedAdminComptesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/journal': {
      id: '/_authenticated/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AuthenticatedAdminJournalRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modeles-ia': {
      id: '/_authenticated/admin/modeles-ia'
      path: '/modeles-ia'
      fullPath: '/admin/modeles-ia'
      preLoaderRoute: typeof AuthenticatedAdminModelesIaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/promos': {
      id: '/_authenticated/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AuthenticatedAdminPromosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/retraits': {
      id: '/_authenticated/admin/retraits'
      path: '/retraits'
      fullPath: '/admin/retraits'
      preLoaderRoute: typeof AuthenticatedAdminRetraitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tendances': {
      id: '/_authenticated/admin/tendances'
      path: '/tendances'
      fullPath: '/admin/tendances'
      preLoaderRoute: typeof AuthenticatedAdminTendancesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/trafic': {
      id: '/_authenticated/admin/trafic'
      path: '/trafic'
      fullPath: '/admin/trafic'
      preLoaderRoute: typeof AuthenticatedAdminTraficRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/verification': {
      id: '/_authenticated/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AuthenticatedAdminVerificationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/analyses': {
      id: '/_authenticated/dashboard/analyses'
      path: '/dashboard/analyses'
      fullPath: '/dashboard/analyses'
      preLoaderRoute: typeof AuthenticatedDashboardAnalysesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/boutique': {
      id: '/_authenticated/dashboard/boutique'
      path: '/dashboard/boutique'
      fullPath: '/dashboard/boutique'
      preLoaderRoute: typeof AuthenticatedDashboardBoutiqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/collections': {
      id: '/_authenticated/dashboard/collections'
      path: '/dashboard/collections'
      fullPath: '/dashboard/collections'
      preLoaderRoute: typeof AuthenticatedDashboardCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/editeur': {
      id: '/_authenticated/dashboard/editeur'
      path: '/dashboard/editeur'
      fullPath: '/dashboard/editeur'
      preLoaderRoute: typeof AuthenticatedDashboardEditeurRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/equipe': {
      id: '/_authenticated/dashboard/equipe'
      path: '/dashboard/equipe'
      fullPath: '/dashboard/equipe'
      preLoaderRoute: typeof AuthenticatedDashboardEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/parametres': {
      id: '/_authenticated/dashboard/parametres'
      path: '/dashboard/parametres'
      fullPath: '/dashboard/parametres'
      preLoaderRoute: typeof AuthenticatedDashboardParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$handle/': {
      id: '/s/$handle/'
      path: '/s/$handle'
      fullPath: '/s/$handle/'
      preLoaderRoute: typeof SHandleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$handle/commande': {
      id: '/s/$handle/commande'
      path: '/s/$handle/commande'
      fullPath: '/s/$handle/commande'
      preLoaderRoute: typeof SHandleCommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$handle/contact': {
      id: '/s/$handle/contact'
      path: '/s/$handle/contact'
      fullPath: '/s/$handle/contact'
      preLoaderRoute: typeof SHandleContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$handle/produits': {
      id: '/s/$handle/produits'
      path: '/s/$handle/produits'
      fullPath: '/s/$handle/produits'
      preLoaderRoute: typeof SHandleProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/clients/': {
      id: '/_authenticated/dashboard/clients/'
      path: '/dashboard/clients'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof AuthenticatedDashboardClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/clients/segments': {
      id: '/_authenticated/dashboard/clients/segments'
      path: '/dashboard/clients/segments'
      fullPath: '/dashboard/clients/segments'
      preLoaderRoute: typeof AuthenticatedDashboardClientsSegmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/commandes/': {
      id: '/_authenticated/dashboard/commandes/'
      path: '/dashboard/commandes'
      fullPath: '/dashboard/commandes/'
      preLoaderRoute: typeof AuthenticatedDashboardCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/commandes/paniers': {
      id: '/_authenticated/dashboard/commandes/paniers'
      path: '/dashboard/commandes/paniers'
      fullPath: '/dashboard/commandes/paniers'
      preLoaderRoute: typeof AuthenticatedDashboardCommandesPaniersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/decouverte/': {
      id: '/_authenticated/dashboard/decouverte/'
      path: '/dashboard/decouverte'
      fullPath: '/dashboard/decouverte/'
      preLoaderRoute: typeof AuthenticatedDashboardDecouverteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/decouverte/boutiques': {
      id: '/_authenticated/dashboard/decouverte/boutiques'
      path: '/dashboard/decouverte/boutiques'
      fullPath: '/dashboard/decouverte/boutiques'
      preLoaderRoute: typeof AuthenticatedDashboardDecouverteBoutiquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/decouverte/favoris': {
      id: '/_authenticated/dashboard/decouverte/favoris'
      path: '/dashboard/decouverte/favoris'
      fullPath: '/dashboard/decouverte/favoris'
      preLoaderRoute: typeof AuthenticatedDashboardDecouverteFavorisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/decouverte/produits': {
      id: '/_authenticated/dashboard/decouverte/produits'
      path: '/dashboard/decouverte/produits'
      fullPath: '/dashboard/decouverte/produits'
      preLoaderRoute: typeof AuthenticatedDashboardDecouverteProduitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/decouverte/publicites': {
      id: '/_authenticated/dashboard/decouverte/publicites'
      path: '/dashboard/decouverte/publicites'
      fullPath: '/dashboard/decouverte/publicites'
      preLoaderRoute: typeof AuthenticatedDashboardDecouvertePublicitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/marketing/': {
      id: '/_authenticated/dashboard/marketing/'
      path: '/dashboard/marketing'
      fullPath: '/dashboard/marketing/'
      preLoaderRoute: typeof AuthenticatedDashboardMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/produits/': {
      id: '/_authenticated/dashboard/produits/'
      path: '/dashboard/produits'
      fullPath: '/dashboard/produits/'
      preLoaderRoute: typeof AuthenticatedDashboardProduitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/produits/ia': {
      id: '/_authenticated/dashboard/produits/ia'
      path: '/dashboard/produits/ia'
      fullPath: '/dashboard/produits/ia'
      preLoaderRoute: typeof AuthenticatedDashboardProduitsIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/produits/nouveau': {
      id: '/_authenticated/dashboard/produits/nouveau'
      path: '/dashboard/produits/nouveau'
      fullPath: '/dashboard/produits/nouveau'
      preLoaderRoute: typeof AuthenticatedDashboardProduitsNouveauRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/billing/ligdicash': {
      id: '/api/public/billing/ligdicash'
      path: '/api/public/billing/ligdicash'
      fullPath: '/api/public/billing/ligdicash'
      preLoaderRoute: typeof ApiPublicBillingLigdicashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/pawapay': {
      id: '/api/public/billing/pawapay'
      path: '/api/public/billing/pawapay'
      fullPath: '/api/public/billing/pawapay'
      preLoaderRoute: typeof ApiPublicBillingPawapayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/decouverte': {
      id: '/api/public/cron/decouverte'
      path: '/api/public/cron/decouverte'
      fullPath: '/api/public/cron/decouverte'
      preLoaderRoute: typeof ApiPublicCronDecouverteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/relances': {
      id: '/api/public/cron/relances'
      path: '/api/public/cron/relances'
      fullPath: '/api/public/cron/relances'
      preLoaderRoute: typeof ApiPublicCronRelancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$handle/produit/': {
      id: '/s/$handle/produit/'
      path: '/s/$handle/produit'
      fullPath: '/s/$handle/produit/'
      preLoaderRoute: typeof SHandleProduitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$handle/produit/$productId': {
      id: '/s/$handle/produit/$productId'
      path: '/s/$handle/produit/$productId'
      fullPath: '/s/$handle/produit/$productId'
      preLoaderRoute: typeof SHandleProduitProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/marketing/emails/$id': {
      id: '/_authenticated/dashboard/marketing/emails/$id'
      path: '/dashboard/marketing/emails/$id'
      fullPath: '/dashboard/marketing/emails/$id'
      preLoaderRoute: typeof AuthenticatedDashboardMarketingEmailsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/marketing/offres/nouveau': {
      id: '/_authenticated/dashboard/marketing/offres/nouveau'
      path: '/dashboard/marketing/offres/nouveau'
      fullPath: '/dashboard/marketing/offres/nouveau'
      preLoaderRoute: typeof AuthenticatedDashboardMarketingOffresNouveauRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/e/c/$rid': {
      id: '/api/public/e/c/$rid'
      path: '/api/public/e/c/$rid'
      fullPath: '/api/public/e/c/$rid'
      preLoaderRoute: typeof ApiPublicECRidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/e/o/$rid': {
      id: '/api/public/e/o/$rid'
      path: '/api/public/e/o/$rid'
      fullPath: '/api/public/e/o/$rid'
      preLoaderRoute: typeof ApiPublicEORidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAbonnementsRoute: typeof AuthenticatedAdminAbonnementsRoute
  AuthenticatedAdminAdministrateursRoute: typeof AuthenticatedAdminAdministrateursRoute
  AuthenticatedAdminBoutiquesRoute: typeof AuthenticatedAdminBoutiquesRoute
  AuthenticatedAdminCommandesRoute: typeof AuthenticatedAdminCommandesRoute
  AuthenticatedAdminComptesRoute: typeof AuthenticatedAdminComptesRoute
  AuthenticatedAdminJournalRoute: typeof AuthenticatedAdminJournalRoute
  AuthenticatedAdminModelesIaRoute: typeof AuthenticatedAdminModelesIaRoute
  AuthenticatedAdminPromosRoute: typeof AuthenticatedAdminPromosRoute
  AuthenticatedAdminRetraitsRoute: typeof AuthenticatedAdminRetraitsRoute
  AuthenticatedAdminTendancesRoute: typeof AuthenticatedAdminTendancesRoute
  AuthenticatedAdminTraficRoute: typeof AuthenticatedAdminTraficRoute
  AuthenticatedAdminVerificationRoute: typeof AuthenticatedAdminVerificationRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAbonnementsRoute: AuthenticatedAdminAbonnementsRoute,
    AuthenticatedAdminAdministrateursRoute:
      AuthenticatedAdminAdministrateursRoute,
    AuthenticatedAdminBoutiquesRoute: AuthenticatedAdminBoutiquesRoute,
    AuthenticatedAdminCommandesRoute: AuthenticatedAdminCommandesRoute,
    AuthenticatedAdminComptesRoute: AuthenticatedAdminComptesRoute,
    AuthenticatedAdminJournalRoute: AuthenticatedAdminJournalRoute,
    AuthenticatedAdminModelesIaRoute: AuthenticatedAdminModelesIaRoute,
    AuthenticatedAdminPromosRoute: AuthenticatedAdminPromosRoute,
    AuthenticatedAdminRetraitsRoute: AuthenticatedAdminRetraitsRoute,
    AuthenticatedAdminTendancesRoute: AuthenticatedAdminTendancesRoute,
    AuthenticatedAdminTraficRoute: AuthenticatedAdminTraficRoute,
    AuthenticatedAdminVerificationRoute: AuthenticatedAdminVerificationRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardAnalysesRoute: typeof AuthenticatedDashboardAnalysesRoute
  AuthenticatedDashboardBoutiqueRoute: typeof AuthenticatedDashboardBoutiqueRoute
  AuthenticatedDashboardCollectionsRoute: typeof AuthenticatedDashboardCollectionsRoute
  AuthenticatedDashboardEditeurRoute: typeof AuthenticatedDashboardEditeurRoute
  AuthenticatedDashboardEquipeRoute: typeof AuthenticatedDashboardEquipeRoute
  AuthenticatedDashboardParametresRoute: typeof AuthenticatedDashboardParametresRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardClientsSegmentsRoute: typeof AuthenticatedDashboardClientsSegmentsRoute
  AuthenticatedDashboardCommandesPaniersRoute: typeof AuthenticatedDashboardCommandesPaniersRoute
  AuthenticatedDashboardDecouverteBoutiquesRoute: typeof AuthenticatedDashboardDecouverteBoutiquesRoute
  AuthenticatedDashboardDecouverteFavorisRoute: typeof AuthenticatedDashboardDecouverteFavorisRoute
  AuthenticatedDashboardDecouverteProduitsRoute: typeof AuthenticatedDashboardDecouverteProduitsRoute
  AuthenticatedDashboardDecouvertePublicitesRoute: typeof AuthenticatedDashboardDecouvertePublicitesRoute
  AuthenticatedDashboardProduitsIaRoute: typeof AuthenticatedDashboardProduitsIaRoute
  AuthenticatedDashboardProduitsNouveauRoute: typeof AuthenticatedDashboardProduitsNouveauRoute
  AuthenticatedDashboardClientsIndexRoute: typeof AuthenticatedDashboardClientsIndexRoute
  AuthenticatedDashboardCommandesIndexRoute: typeof AuthenticatedDashboardCommandesIndexRoute
  AuthenticatedDashboardDecouverteIndexRoute: typeof AuthenticatedDashboardDecouverteIndexRoute
  AuthenticatedDashboardMarketingIndexRoute: typeof AuthenticatedDashboardMarketingIndexRoute
  AuthenticatedDashboardProduitsIndexRoute: typeof AuthenticatedDashboardProduitsIndexRoute
  AuthenticatedDashboardMarketingEmailsIdRoute: typeof AuthenticatedDashboardMarketingEmailsIdRoute
  AuthenticatedDashboardMarketingOffresNouveauRoute: typeof AuthenticatedDashboardMarketingOffresNouveauRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardAnalysesRoute: AuthenticatedDashboardAnalysesRoute,
  AuthenticatedDashboardBoutiqueRoute: AuthenticatedDashboardBoutiqueRoute,
  AuthenticatedDashboardCollectionsRoute:
    AuthenticatedDashboardCollectionsRoute,
  AuthenticatedDashboardEditeurRoute: AuthenticatedDashboardEditeurRoute,
  AuthenticatedDashboardEquipeRoute: AuthenticatedDashboardEquipeRoute,
  AuthenticatedDashboardParametresRoute: AuthenticatedDashboardParametresRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardClientsSegmentsRoute:
    AuthenticatedDashboardClientsSegmentsRoute,
  AuthenticatedDashboardCommandesPaniersRoute:
    AuthenticatedDashboardCommandesPaniersRoute,
  AuthenticatedDashboardDecouverteBoutiquesRoute:
    AuthenticatedDashboardDecouverteBoutiquesRoute,
  AuthenticatedDashboardDecouverteFavorisRoute:
    AuthenticatedDashboardDecouverteFavorisRoute,
  AuthenticatedDashboardDecouverteProduitsRoute:
    AuthenticatedDashboardDecouverteProduitsRoute,
  AuthenticatedDashboardDecouvertePublicitesRoute:
    AuthenticatedDashboardDecouvertePublicitesRoute,
  AuthenticatedDashboardProduitsIaRoute: AuthenticatedDashboardProduitsIaRoute,
  AuthenticatedDashboardProduitsNouveauRoute:
    AuthenticatedDashboardProduitsNouveauRoute,
  AuthenticatedDashboardClientsIndexRoute:
    AuthenticatedDashboardClientsIndexRoute,
  AuthenticatedDashboardCommandesIndexRoute:
    AuthenticatedDashboardCommandesIndexRoute,
  AuthenticatedDashboardDecouverteIndexRoute:
    AuthenticatedDashboardDecouverteIndexRoute,
  AuthenticatedDashboardMarketingIndexRoute:
    AuthenticatedDashboardMarketingIndexRoute,
  AuthenticatedDashboardProduitsIndexRoute:
    AuthenticatedDashboardProduitsIndexRoute,
  AuthenticatedDashboardMarketingEmailsIdRoute:
    AuthenticatedDashboardMarketingEmailsIdRoute,
  AuthenticatedDashboardMarketingOffresNouveauRoute:
    AuthenticatedDashboardMarketingOffresNouveauRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TendancesRouteChildren {
  TendancesIdRoute: typeof TendancesIdRoute
  TendancesIndexRoute: typeof TendancesIndexRoute
}

const TendancesRouteChildren: TendancesRouteChildren = {
  TendancesIdRoute: TendancesIdRoute,
  TendancesIndexRoute: TendancesIndexRoute,
}

const TendancesRouteWithChildren = TendancesRoute._addFileChildren(
  TendancesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AideRoute: AideRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  LoginRoute: LoginRoute,
  LogoPreviewRoute: LogoPreviewRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  OnboardingRoute: OnboardingRoute,
  RejoindreRoute: RejoindreRoute,
  SignupRoute: SignupRoute,
  TendancesRoute: TendancesRouteWithChildren,
  VerificationRoute: VerificationRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
  SHandleCommandeRoute: SHandleCommandeRoute,
  SHandleContactRoute: SHandleContactRoute,
  SHandleProduitsRoute: SHandleProduitsRoute,
  SHandleIndexRoute: SHandleIndexRoute,
  ApiPublicBillingLigdicashRoute: ApiPublicBillingLigdicashRoute,
  ApiPublicBillingPawapayRoute: ApiPublicBillingPawapayRoute,
  ApiPublicCronDecouverteRoute: ApiPublicCronDecouverteRoute,
  ApiPublicCronRelancesRoute: ApiPublicCronRelancesRoute,
  SHandleProduitProductIdRoute: SHandleProduitProductIdRoute,
  SHandleProduitIndexRoute: SHandleProduitIndexRoute,
  ApiPublicECRidRoute: ApiPublicECRidRoute,
  ApiPublicEORidRoute: ApiPublicEORidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
